<a href="https://colab.research.google.com/github/purpledreamzero/python-learning/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.DataFrame({
    "商品": ["可樂", "咖啡", "牛奶", "麵包", "茶"],
    "類別": ["飲料", "飲料", "乳品", "食品", "飲料"],
    "數量": [50, 30, 20, 15, 40],
    "單價": [25, 60, 35, 45, 30]
})

print(df)

   商品  類別  數量  單價
0  可樂  飲料  50  25
1  咖啡  飲料  30  60
2  牛奶  乳品  20  35
3  麵包  食品  15  45
4   茶  飲料  40  30

In [2]:
df[['商品', '類別', '數量']]

   商品  類別  數量
0  可樂  飲料  50
1  咖啡  飲料  30
2  牛奶  乳品  20
3  麵包  食品  15
4   茶  飲料  40

In [3]:
df[df["單價"] > 40]

   商品  類別  數量  單價
1  咖啡  飲料  30  60
3  麵包  食品  15  45

In [4]:
df[df["數量"] > 30]

   商品  類別  數量  單價
0  可樂  飲料  50  25
4   茶  飲料  40  30

In [5]:
df["數量"] > 30

0     True
1    False
2    False
3    False
4     True
Name: 數量, dtype: bool

In [6]:
df["商品"].count()

np.int64(5)

In [7]:
print(df[df["商品"] == "麵包"])

   商品  類別  數量  單價
3  麵包  食品  15  45

In [8]:
df.loc[len(df)] = ['咖哩', '食品', 15, 45]
print(df)

   商品  類別  數量  單價
0  可樂  飲料  50  25
1  咖啡  飲料  30  60
2  牛奶  乳品  20  35
3  麵包  食品  15  45
4   茶  飲料  40  30
5  咖哩  食品  15  45

In [10]:
import yfinance as yf
import pandas as pd

def get_stock(ticker='2330.TW'):
    # 1. 下載股票資料
    df_2330 = yf.download(
        ticker,
        period='2y',
        auto_adjust=True,
        progress=False
    )

    # 2. 檢查是否有下載到資料
    if df_2330.empty:
        raise ValueError(f'無法取得股票資料：{ticker}')

    # 3. 計算移動平均線
    close = df_2330['Close']

    df_2330['MA20'] = close.rolling(20).mean()
    df_2330['MA60'] = close.rolling(60).mean()
    df_2330['MA120'] = close.rolling(120).mean()
    df_2330['MA240'] = close.rolling(240).mean()

    # 4. 回傳完整資料
    return df_2330


# 呼叫函式
df_2330 = get_stock()

print(df_2330.tail())

Price        Close    High     Low    Open    Volume         MA20  \
Ticker     2330.TW 2330.TW 2330.TW 2330.TW   2330.TW
Date
2026-10-12  2540.0  2550.0  2510.0  2510.0  20448010  2478.837537
2026-10-13  2490.0  2510.0  2490.0  2500.0  34572010  2481.197070
2026-10-14  2490.0  2535.0  2490.0  2505.0  23305802  2485.550732
2026-10-15  2440.0  2450.0  2420.0  2420.0  48190233  2488.900000
2026-10-16  2420.0  2445.0  2420.0  2430.0  33490270  2491.000000

Price              MA60        MA120        MA240
Ticker
Date
2026-10-12  2410.200041  2356.033642  2004.629196
2026-10-13  2410.654199  2360.002938  2008.973980
2026-10-14  2414.099552  2363.765066  2013.236440
2026-10-15  2416.213037  2367.110527  2017.434633
2026-10-16  2416.497591  2370.040719  2021.426007