<a href="https://colab.research.google.com/github/purpledreamzero/python-learning/blob/main/%E7%88%AC%E8%9F%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
from bs4 import BeautifulSoup

url = "https://books.toscrape.com/"

response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

title = soup.find("h1")

# print(response.status_code)
# print(response.text[:1000])

print(title.text)

All products

In [ ]:

import requests
from bs4 import BeautifulSoup

url = "https://books.toscrape.com/"

response = requests.get(url, timeout=15)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

title = soup.find("h1")

if title:
    print(title.get_text(strip=True))
else:
    print("找不到 h1 標題")

All products

In [ ]:
import requests # 匯入 requests 套件

x = requests.get("https://books.toscrape.com/") # 向指定網址發送 HTTP GET 請求

print(x.status_code) # 取得 HTTP 狀態碼

print(x.reason) # 取得 HTTP 狀態描述

print(x.apparent_encoding) # 根據網頁內容推測文字編碼

200
OK
utf-8

In [ ]:

import requests
from bs4 import BeautifulSoup
import pandas as pd

# 1. 指定目標網站
url = "https://books.toscrape.com/"

# 2. 取得網頁
response = requests.get(url, timeout=15)
response.raise_for_status()

# 3. 解析 HTML
soup = BeautifulSoup(response.text, "html.parser")

# 4. 找出每一本書
books = soup.select("article.product_pod")

# 5. 擷取書名、價格、庫存狀態
data = []

for book in books:
    title = book.h3.a["title"]
    price = book.select_one(".price_color").get_text(strip=True)
    stock = book.select_one(".availability").get_text(strip=True)

    data.append({
        "書名": title,
        "價格": price,
        "庫存狀態": stock
    })

# 6. 整理成表格
df = pd.DataFrame(data)

print("抓取筆數：", len(df))
display(df)

抓取筆數： 20

                                                   書名       價格      庫存狀態
0                                A Light in the Attic  Â£51.77  In stock
1                                  Tipping the Velvet  Â£53.74  In stock
2                                          Soumission  Â£50.10  In stock
3                                       Sharp Objects  Â£47.82  In stock
4               Sapiens: A Brief History of Humankind  Â£54.23  In stock
5                                     The Requiem Red  Â£22.65  In stock
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34  In stock
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93  In stock
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60  In stock
9                                     The Black Maria  Â£52.15  In stock
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99  In stock
11                              Shakespeare's Sonnets  Â£20.66  In stock
12                                        Set Me Free  Â£17.46  In stock
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29  In stock
14                          Rip it Up and Start Again  Â£35.02  In stock
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25  In stock
16                                               Olio  Â£23.88  In stock
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59  In stock
18                       Libertarianism for Beginners  Â£51.33  In stock
19                            It's Only the Himalayas  Â£45.17  In stock

In [ ]:

import requests
from bs4 import BeautifulSoup
import pandas as pd

# 1. 設定要抓取的兩個頁面
urls = [
    "https://books.toscrape.com/",
    "https://books.toscrape.com/catalogue/page-2.html"
]

# 2. 建立一份共同的資料清單
data = []

# 3. 逐頁抓取
for url in urls:
    response = requests.get(url, timeout=15)
    response.raise_for_status()

    soup = BeautifulSoup(response.text, "html.parser")
    books = soup.select("article.product_pod")

    # 4. 逐本書擷取資料
    for book in books:
        title = book.h3.a["title"]
        price = book.select_one(".price_color").get_text(strip=True)
        stock = book.select_one(".availability").get_text(strip=True)

        data.append({
            "書名": title,
            "價格": price,
            "庫存狀態": stock
        })

# 5. 合併成一份表格
df = pd.DataFrame(data)

print("總抓取筆數：", len(df))
display(df)

總抓取筆數： 40

                                                   書名       價格      庫存狀態
0                                A Light in the Attic  Â£51.77  In stock
1                                  Tipping the Velvet  Â£53.74  In stock
2                                          Soumission  Â£50.10  In stock
3                                       Sharp Objects  Â£47.82  In stock
4               Sapiens: A Brief History of Humankind  Â£54.23  In stock
5                                     The Requiem Red  Â£22.65  In stock
6   The Dirty Little Secrets of Getting Your Dream...  Â£33.34  In stock
7   The Coming Woman: A Novel Based on the Life of...  Â£17.93  In stock
8   The Boys in the Boat: Nine Americans and Their...  Â£22.60  In stock
9                                     The Black Maria  Â£52.15  In stock
10     Starving Hearts (Triangular Trade Trilogy, #1)  Â£13.99  In stock
11                              Shakespeare's Sonnets  Â£20.66  In stock
12                                        Set Me Free  Â£17.46  In stock
13  Scott Pilgrim's Precious Little Life (Scott Pi...  Â£52.29  In stock
14                          Rip it Up and Start Again  Â£35.02  In stock
15  Our Band Could Be Your Life: Scenes from the A...  Â£57.25  In stock
16                                               Olio  Â£23.88  In stock
17  Mesaerion: The Best Science Fiction Stories 18...  Â£37.59  In stock
18                       Libertarianism for Beginners  Â£51.33  In stock
19                            It's Only the Himalayas  Â£45.17  In stock
20                                        In Her Wake  Â£12.84  In stock
21                                    How Music Works  Â£37.32  In stock
22  Foolproof Preserving: A Guide to Small Batch J...  Â£30.52  In stock
23                         Chase Me (Paris Nights #2)  Â£25.27  In stock
24                                         Black Dust  Â£34.53  In stock
25                      Birdsong: A Story in Pictures  Â£54.64  In stock
26  America's Cradle of Quarterbacks: Western Penn...  Â£22.50  In stock
27                     Aladdin and His Wonderful Lamp  Â£53.13  In stock
28  Worlds Elsewhere: Journeys Around Shakespeareâ...  Â£40.30  In stock
29                                     Wall and Piece  Â£44.18  In stock
30  The Four Agreements: A Practical Guide to Pers...  Â£17.66  In stock
31  The Five Love Languages: How to Express Heartf...  Â£31.05  In stock
32                                  The Elephant Tree  Â£23.82  In stock
33                             The Bear and the Piano  Â£36.89  In stock
34                                     Sophie's World  Â£15.94  In stock
35                                        Penny Maybe  Â£33.29  In stock
36     Maude (1883-1993):She Grew Up with the country  Â£18.02  In stock
37                               In a Dark, Dark Wood  Â£19.63  In stock
38                                Behind Closed Doors  Â£52.22  In stock
39                     You can't bury them all: Poems  Â£33.63  In stock

Requests GET、Response、狀態碼與錯誤處理

1.發送 GET 請求

使用 requests.get() 向網站發送 HTTP GET 請求，取得伺服器回傳的 Response 物件。

import requests

url = "https://books.toscrape.com/"
response = requests.get(url)

2.查看回應內容

print(response)
print(response.status_code)
print(response.text[:200])

response：HTTP 回應物件。

response.status_code：HTTP 狀態碼。

response.text：回應的文字內容，通常包含 HTML。

3.設定 timeout

response = requests.get(url, timeout=3)

設定連線與讀取逾時限制，避免程式無限期等待。逾時可能引發 requests.exceptions.Timeout。

4.使用 raise_for_status()

response.raise_for_status()

當回應狀態碼為 HTTP 4xx 或 5xx 時，會拋出 HTTP 錯誤例外。

5.使用 try / except 處理錯誤

import requests

url = "https://books.toscrape.com/"

try:
    response = requests.get(url, timeout=3)
    response.raise_for_status()
    print("請求成功!")

except requests.exceptions.RequestException as error:
    print("請求失敗:", error)

6.紀錄

正常頁面測試：HTTP 200，請求成功。

不存在的頁面測試：HTTP 404，成功進入錯誤處理區塊。


7.重點

掌握 GET 請求、Response 物件、HTTP 狀態碼、timeout、raise_for_status() 與 try / except 的基本用途。

In [ ]:
import requests

ur1 = "https://books.toscrape.com/"

response = requests.get(ur1, timeout=3)  #發送 GET 請求

print(response)

print(response.status_code)  #查看 HTTP 狀態碼
print(response.text[:200]) #讀取 HTML 文字

In [ ]:
import requests

try:
  response = requests.get(ur1, timeout=3) #設定逾時限制
  print(response.status_code)
except requests.exceptions.Timeout:
  print("請求逾時,請稍後再試")

In [ ]:
import requests

try:
  response = requests.get(ur1, timeout=3) #設定逾時限制
  print(response.status_code)
except requests.exceptions.Timeout:
  print("請求逾時,請稍後再試")

In [ ]:
from logging import exception
import requests

url = "https://books.toscrape.com/"

try:
  response = requests.get(ur1, timeout=3)

  if response.status_code == 200:
    print("請求成功!")

  else:
    print("HTTP 狀態碼:", response.status_code)
except requests.exceptions.RequestException as error:
  print("請求失敗:", error)